### ISSUE TITLE
JOSM plugin signpost detection bug

### ISSUE THREAD

**Issue by rich123** [openstreetcam/josm-plugin#26]
This bug is reproducable for me by following the steps below.  At the end, I get the final image every time.

1) Start a fresh JOSM instance:
![osc1](https://user-images.githubusercontent.com/305956/44784013-2a4e9700-ab5a-11e8-8955-7b8ee6ee0418.png)

2) Download this area:
![osc2](https://user-images.githubusercontent.com/305956/44784030-35a1c280-ab5a-11e8-979a-a111f21a48c4.png)

The URL JOSM uses to download the area above is: INFO: GET https://api.openstreetmap.org/api/0.6/map?bbox=-77.0784004,38.8017005,-77.0767804,38.802823 -> 200

3) Maximize the JOSM window, zoom in to see the ways and the OSC track, and move the OSC layer above the data layer:
![osc3](https://user-images.githubusercontent.com/305956/44784323-4141b900-ab5b-11e8-9f5a-61f5a065c4c0.png)

4) Next, click on the OSC track photo dot labeled "1" in the image above.  Then, click on the OSC track photo dot labeled "2" in the image above.  Sometimes when clicking "1" but always when clicking on "1" then on "2" I get teleported to this view below in JOSM:

![osc4](https://user-images.githubusercontent.com/305956/44784339-4e5ea800-ab5b-11e8-939c-139bc8a9968d.png)

**Comment by beataj-telenav** [comment]
Thank you for reporting the issue. There was an issue with the OSC images, the issue was solved meanwhile. Let me know if you encounter further issues.

**Comment by rich123** [comment]
It has now been about 12 hours since your reply, I still get the 'teleportation' effect to the mass of street signs view in JOSM when I follow the same steps I outlined above.

**Comment by beataj-telenav** [comment]
I have double checked the issue and we are working on fixing it (it is a data issue, not a OSC plugin). Thanks for finding the problem.
